### ISSUE TITLE
Bowtie and Samtools Error

### ISSUE THREAD

**Issue by ghost** [GMAP-fusion/GMAP-fusion#1]
Hi,

I'm trying to run the DISCASCM - GMAP-fusion pipeline. I had some issues with GMAP-fusion not handling paths properly (if the fq and trinity_out_dir.Trinity.fasta files are in different locations) though creating a symlink in the run directory seemed to have solved it. Now I have the following error so it seems some of the commands might need tweaking or something in my files or command is wrong. Thanks in advance for help!

```
GMAP-fusion --CPU 12 \
--transcripts trinity_out_dir.Trinity.fasta \
--genome_lib_dir $HOME/genome/fusion_index \
--left_fq Sample1_R1.fq --right_fq Sample1_R2.fq \
--output GMAP
```

```
* Running CMD: bash -c "set pipefail -o && bowtie2 -k10 -p 4 --no-mixed --no-discordant --very-fast --end-to-end  -x /directory/data/rna_seq/fusion/secondary/Sample1/GMAP/gmap_fusion_intermediates_dir/$
owtie2_target -1 /directory/data/rna_seq/fusion/secondary/Sample1/Sample1_R1.fq -2 /directory/data/rna_seq/fusion/secondary/Sample1/Sample1_R2.fq  | samtools view -F 4 -Sb - | s$
mtools sort -@ 4 - /directory/data/rna_seq/fusion/secondary/Sample1/GMAP/gmap_fusion_in$
ermediates_dir/gmap.map.gff3.chims_described.revised.fasta.bowtie2"
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  -@, --threads INT
             Set number of sorting and compression threads [1]
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
(ERR): bowtie2-align died with signal 13 (PIPE) 
```

**Comment by brianjohnhaas** [comment]
Hi

It looks like it might be a compatibility problem with the samtools you're using.  The latest samtools software isn't apparently backwards compatible with regard to certain parameters.   Can you try using an old version of samtools?  Just put it in your PATH setting before the other samtools version.

I'll look more into this later.  Please let me know how it goes in the meantime.

Best,

-Brian
(by iPhone)

**Comment by ghost** [comment]
Hi Brian,

Thanks for the advice - it indeed was the newer samtools that caused the issue. Probably worth adding a remark in the wiki to use the older version (which does not want to compile with newer zlib library and needs a slight modification in the makefile).

Again, thanks for your rapid replies!
